apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sfm-ingress
  namespace: sfm
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: 20.76.11.164.nip.io
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: sfm-backend-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sfm-frontend-service
            port:
              number: 80
